patcher-args = "--striplibs=arm64-v8a"

[YouTube]
package-name = "com.google.android.youtube"
app-source = "rjaakash/peachmeow-store"
patches-version = "all"
cli-version = "all"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"

["YouTube Material You"]
package-name = "com.google.android.youtube"
app-source = "rjaakash/peachmeow-store"
patches-version = "all"
cli-version = "all"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true -e 'Theme' -olightThemeBackgroundColor='Material You' -odarkThemeBackgroundColor='Material You'"
